spring:
  application:
    name: Employees API
  datasource:
    url: jdbc:h2:mem:employees
    username: dmsb
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
